{
  "hash": "b7f061198299793743e5566b36e98f26",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Class10 Structural Bioinformatics Pt1 (11/01/24)\"\nauthor: \"Janie Chang-Weinberg (A69037446)\"\nformat: pdf\n---\n\n\n\nWhat is in the PDB database anyway?\nSummary data grabbed from:\nhttps://www.rcsb.org/stats/summary\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npdbstats <- read.csv(\"PDB_stats_summaryfile.csv\", row.names = 1)\npdbstats\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                          X.ray     EM    NMR Multiple.methods Neutron Other\nProtein (only)          167,317 15,698 12,534              208      77    32\nProtein/Oligosaccharide   9,645  2,639     34                8       2     0\nProtein/NA                8,735  4,718    286                7       0     0\nNucleic acid (only)       2,869    138  1,507               14       3     1\nOther                       170     10     33                0       0     0\nOligosaccharide (only)       11      0      6                1       0     4\n                          Total\nProtein (only)          195,866\nProtein/Oligosaccharide  12,328\nProtein/NA               13,746\nNucleic acid (only)       4,532\nOther                       213\nOligosaccharide (only)       22\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nx <- pdbstats$Total\nx\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"195,866\" \"12,328\"  \"13,746\"  \"4,532\"   \"213\"     \"22\"     \n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n#as.numeric(x): Warning: NAs introduced by coercion[1]  NA  NA  NA  NA 213  22\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\ngsub(',', '', x)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"195866\" \"12328\"  \"13746\"  \"4532\"   \"213\"    \"22\"    \n```\n\n\n:::\n:::\n\n\n\ndoesn't like the commas, ask google. can also use \"claude\" \nuse gsub to replace commas with nothings\n\n\n::: {.cell}\n\n```{.r .cell-code}\nconvertednocomma <- function(x){\n  #remove comma\n  x <- gsub(',', '', x)\n  #convert to numeric\n  x <- as.numeric(x)\n  return(x)\n}\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nconvertednocomma(pdbstats$Total)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 195866  12328  13746   4532    213     22\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nn.tot <- sum(convertednocomma(pdbstats$Total))\nn.tot\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 226707\n```\n\n\n:::\n:::\n\n\n\nThe `apply()` function is very useful as it can take any function and \"Apply\" it over either the ROWS or COLs of a data.frame.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncolSums(apply(pdbstats, 2, convertednocomma))/n.tot\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n           X.ray               EM              NMR Multiple.methods \n    0.8325592064     0.1023479646     0.0635181093     0.0010498132 \n         Neutron            Other            Total \n    0.0003617003     0.0001632063     1.0000000000 \n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n#another way of importing data to avoid issues with commas in the numbas\n#library(readr)\n#read_csv(\"PDB_stats_summaryfile.csv\")\n```\n:::\n\n\n\nQ1: What percentage of structures in the PDB are solved by X-Ray and Electron Microscopy?\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nn.xray <- sum(convertednocomma(pdbstats$X.ray))\nn.em <- sum(convertednocomma(pdbstats$EM))\n\nxraypercent <- ((n.xray/n.tot)*100)\nempercent <- ((n.em/n.tot)*100)\n\nxraypercent\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 83.25592\n```\n\n\n:::\n\n```{.r .cell-code}\nempercent\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 10.2348\n```\n\n\n:::\n:::\n\n\n>83.26% (xray%), 10.23% (EM%)\n\nQ2. What proportion of structures in the PDB are protein?\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nn.totalprots <- 195866/n.tot\n\nn.totalprots\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.863961\n```\n\n\n:::\n:::\n\n\n> 86.4%\n\nQ3: Type HIV in the PDB website search box on the home page and determine how many HIV-1 protease structures are in the current PDB?\n\n> 4,640\n\n## Using Mol*\n\n![My first image from Mol-star :D](1HSG.png)\n\nQ4: Water molecules normally have 3 atoms. Why do we see just one atom per water molecule in this structure?\n\n>Cannot see Hydrogen at this resolution, the only atom being displayed here is oxygen. \n\nQ5: There is a critical “conserved” water molecule in the binding site. Can you identify this water molecule? What residue number does this water molecule have\n\n> This water molecule's residue number is HOH 308\n\nQ6: Generate and save a figure clearly showing the two distinct chains of HIV-protease along with the ligand. You might also consider showing the catalytic residues ASP 25 in each chain and the critical water (we recommend “Ball & Stick” for these side-chains). Add this figure to your Quarto document.\n\n>![with Aspartate residues and H2O mol](1HSG_withwater.png)\n\n## Use the Bio3D package for structural Bioinformatics\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(bio3d)\n\npdb <- read.pdb(\"1hsg\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  Note: Accessing on-line PDB file\n```\n\n\n:::\n\n```{.r .cell-code}\npdb\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n Call:  read.pdb(file = \"1hsg\")\n\n   Total Models#: 1\n     Total Atoms#: 1686,  XYZs#: 5058  Chains#: 2  (values: A B)\n\n     Protein Atoms#: 1514  (residues/Calpha atoms#: 198)\n     Nucleic acid Atoms#: 0  (residues/phosphate atoms#: 0)\n\n     Non-protein/nucleic Atoms#: 172  (residues: 128)\n     Non-protein/nucleic resid values: [ HOH (127), MK1 (1) ]\n\n   Protein sequence:\n      PQITLWQRPLVTIKIGGQLKEALLDTGADDTVLEEMSLPGRWKPKMIGGIGGFIKVRQYD\n      QILIEICGHKAIGTVLVGPTPVNIIGRNLLTQIGCTLNFPQITLWQRPLVTIKIGGQLKE\n      ALLDTGADDTVLEEMSLPGRWKPKMIGGIGGFIKVRQYDQILIEICGHKAIGTVLVGPTP\n      VNIIGRNLLTQIGCTLNF\n\n+ attr: atom, xyz, seqres, helix, sheet,\n        calpha, remark, call\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nattributes(pdb)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n$names\n[1] \"atom\"   \"xyz\"    \"seqres\" \"helix\"  \"sheet\"  \"calpha\" \"remark\" \"call\"  \n\n$class\n[1] \"pdb\" \"sse\"\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nhead(pdb$atom)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  type eleno elety  alt resid chain resno insert      x      y     z o     b\n1 ATOM     1     N <NA>   PRO     A     1   <NA> 29.361 39.686 5.862 1 38.10\n2 ATOM     2    CA <NA>   PRO     A     1   <NA> 30.307 38.663 5.319 1 40.62\n3 ATOM     3     C <NA>   PRO     A     1   <NA> 29.760 38.071 4.022 1 42.64\n4 ATOM     4     O <NA>   PRO     A     1   <NA> 28.600 38.302 3.676 1 43.40\n5 ATOM     5    CB <NA>   PRO     A     1   <NA> 30.508 37.541 6.342 1 37.87\n6 ATOM     6    CG <NA>   PRO     A     1   <NA> 29.296 37.591 7.162 1 38.40\n  segid elesy charge\n1  <NA>     N   <NA>\n2  <NA>     C   <NA>\n3  <NA>     C   <NA>\n4  <NA>     O   <NA>\n5  <NA>     C   <NA>\n6  <NA>     C   <NA>\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\npdbseq(pdb)[25]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n 25 \n\"D\" \n```\n\n\n:::\n:::\n\n\nQ7. How many amino acids are there in this structure?\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlength(pdbseq(pdb))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 198\n```\n\n\n:::\n:::\n\n\n> There are 198 amino acids in this structure\n\nQ8. Name one of the two non-protein residues?\n\n> HOH (water)\n\nQ9. How many protein chains are in this structure?\n\n> 2\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nadk <- read.pdb(\"6s36\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  Note: Accessing on-line PDB file\n   PDB has ALT records, taking A only, rm.alt=TRUE\n```\n\n\n:::\n\n```{.r .cell-code}\nadk\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n Call:  read.pdb(file = \"6s36\")\n\n   Total Models#: 1\n     Total Atoms#: 1898,  XYZs#: 5694  Chains#: 1  (values: A)\n\n     Protein Atoms#: 1654  (residues/Calpha atoms#: 214)\n     Nucleic acid Atoms#: 0  (residues/phosphate atoms#: 0)\n\n     Non-protein/nucleic Atoms#: 244  (residues: 244)\n     Non-protein/nucleic resid values: [ CL (3), HOH (238), MG (2), NA (1) ]\n\n   Protein sequence:\n      MRIILLGAPGAGKGTQAQFIMEKYGIPQISTGDMLRAAVKSGSELGKQAKDIMDAGKLVT\n      DELVIALVKERIAQEDCRNGFLLDGFPRTIPQADAMKEAGINVDYVLEFDVPDELIVDKI\n      VGRRVHAPSGRVYHVKFNPPKVEGKDDVTGEELTTRKDDQEETVRKRLVEYHQMTAPLIG\n      YYSKEAEAGNTKYAKVDGTKPVAEVRADLEKILG\n\n+ attr: atom, xyz, seqres, helix, sheet,\n        calpha, remark, call\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(r3dmol)\nsource(\"https://tinyurl.com/viewpdb\")\n\nlibrary(shiny)\nview.pdb(pdb)\n```\n\n::: {.cell-output-display}\n![](JCW_110124_bioinfo_Class10_files/figure-pdf/unnamed-chunk-18-1.pdf){fig-pos='H'}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nmodes <- nma(adk)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n Building Hessian...\t\tDone in 0.018 seconds.\n Diagonalizing Hessian...\tDone in 0.342 seconds.\n```\n\n\n:::\n\n```{.r .cell-code}\nplot(modes)\n```\n\n::: {.cell-output-display}\n![](JCW_110124_bioinfo_Class10_files/figure-pdf/unnamed-chunk-19-1.pdf){fig-pos='H'}\n:::\n\n```{.r .cell-code}\nmktrj(modes, pdb=adk, file='adk.pdb') #give it the pdb= thing to have proper seq\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nmktrj(modes, file=\"adk_m7.pdb\")\n```\n:::\n\n\n\n\nQ10. Which of the packages above is found only on BioConductor and not CRAN?\n\n> biocmanager\n\nQ.11 Which of the above packages is not found on BioConductor or CRAN?\n\n> bio3d \n\nQ.12 True or False? Functions from the devtools package can be used to install packages from GitHub and BitBucket?\n\n> True\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(bio3d)\naa <- get.seq(\"1ake_A\")\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in get.seq(\"1ake_A\"): Removing existing file: seqs.fasta\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\nFetching... Please wait. Done.\n```\n\n\n:::\n\n```{.r .cell-code}\naa\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n             1        .         .         .         .         .         60 \npdb|1AKE|A   MRIILLGAPGAGKGTQAQFIMEKYGIPQISTGDMLRAAVKSGSELGKQAKDIMDAGKLVT\n             1        .         .         .         .         .         60 \n\n            61        .         .         .         .         .         120 \npdb|1AKE|A   DELVIALVKERIAQEDCRNGFLLDGFPRTIPQADAMKEAGINVDYVLEFDVPDELIVDRI\n            61        .         .         .         .         .         120 \n\n           121        .         .         .         .         .         180 \npdb|1AKE|A   VGRRVHAPSGRVYHVKFNPPKVEGKDDVTGEELTTRKDDQEETVRKRLVEYHQMTAPLIG\n           121        .         .         .         .         .         180 \n\n           181        .         .         .   214 \npdb|1AKE|A   YYSKEAEAGNTKYAKVDGTKPVAEVRADLEKILG\n           181        .         .         .   214 \n\nCall:\n  read.fasta(file = outfile)\n\nClass:\n  fasta\n\nAlignment dimensions:\n  1 sequence rows; 214 position columns (214 non-gap, 0 gap) \n\n+ attr: id, ali, call\n```\n\n\n:::\n:::\n\n\n\nQ13. How many amino acids are in this sequence, i.e. how long is this sequence?\n\n> There are 214 AAs\n\n##Blast or hmmer search \n\n\n::: {.cell}\n\n```{.r .cell-code}\nb <- blast.pdb(aa)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n Searching ... please wait (updates every 5 seconds) RID = JP0JPEGF016 \n .................\n Reporting 85 hits\n```\n\n\n:::\n:::\n\n\n\n##Plot a summary of search results:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhits <- plot(b)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  * Possible cutoff values:    197 11 \n            Yielding Nhits:    19 85 \n\n  * Chosen cutoff value of:    197 \n            Yielding Nhits:    19 \n```\n\n\n:::\n\n::: {.cell-output-display}\n![](JCW_110124_bioinfo_Class10_files/figure-pdf/unnamed-chunk-23-1.pdf){fig-pos='H'}\n:::\n:::\n\n\n\n##List some \"Top Hits\" and download their .pdb files:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhead(hits$pdb.id)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"1AKE_A\" \"8BQF_A\" \"4X8M_A\" \"6S36_A\" \"8Q2B_A\" \"8RJ9_A\"\n```\n\n\n:::\n\n```{.r .cell-code}\nfiles <- get.pdb(hits$pdb.id, path=\"pdbs\", split=TRUE, gzip=TRUE)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in get.pdb(hits$pdb.id, path = \"pdbs\", split = TRUE, gzip = TRUE):\npdbs/1AKE.pdb.gz exists. Skipping download\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in get.pdb(hits$pdb.id, path = \"pdbs\", split = TRUE, gzip = TRUE):\npdbs/8BQF.pdb.gz exists. Skipping download\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in get.pdb(hits$pdb.id, path = \"pdbs\", split = TRUE, gzip = TRUE):\npdbs/4X8M.pdb.gz exists. Skipping download\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in get.pdb(hits$pdb.id, path = \"pdbs\", split = TRUE, gzip = TRUE):\npdbs/6S36.pdb.gz exists. Skipping download\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in get.pdb(hits$pdb.id, path = \"pdbs\", split = TRUE, gzip = TRUE):\npdbs/8Q2B.pdb.gz exists. Skipping download\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in get.pdb(hits$pdb.id, path = \"pdbs\", split = TRUE, gzip = TRUE):\npdbs/8RJ9.pdb.gz exists. Skipping download\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in get.pdb(hits$pdb.id, path = \"pdbs\", split = TRUE, gzip = TRUE):\npdbs/6RZE.pdb.gz exists. Skipping download\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in get.pdb(hits$pdb.id, path = \"pdbs\", split = TRUE, gzip = TRUE):\npdbs/4X8H.pdb.gz exists. Skipping download\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in get.pdb(hits$pdb.id, path = \"pdbs\", split = TRUE, gzip = TRUE):\npdbs/3HPR.pdb.gz exists. Skipping download\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in get.pdb(hits$pdb.id, path = \"pdbs\", split = TRUE, gzip = TRUE):\npdbs/1E4V.pdb.gz exists. Skipping download\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in get.pdb(hits$pdb.id, path = \"pdbs\", split = TRUE, gzip = TRUE):\npdbs/5EJE.pdb.gz exists. Skipping download\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in get.pdb(hits$pdb.id, path = \"pdbs\", split = TRUE, gzip = TRUE):\npdbs/1E4Y.pdb.gz exists. Skipping download\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in get.pdb(hits$pdb.id, path = \"pdbs\", split = TRUE, gzip = TRUE):\npdbs/3X2S.pdb.gz exists. Skipping download\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in get.pdb(hits$pdb.id, path = \"pdbs\", split = TRUE, gzip = TRUE):\npdbs/6HAP.pdb.gz exists. Skipping download\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in get.pdb(hits$pdb.id, path = \"pdbs\", split = TRUE, gzip = TRUE):\npdbs/6HAM.pdb.gz exists. Skipping download\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in get.pdb(hits$pdb.id, path = \"pdbs\", split = TRUE, gzip = TRUE):\npdbs/4K46.pdb.gz exists. Skipping download\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in get.pdb(hits$pdb.id, path = \"pdbs\", split = TRUE, gzip = TRUE):\npdbs/4NP6.pdb.gz exists. Skipping download\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in get.pdb(hits$pdb.id, path = \"pdbs\", split = TRUE, gzip = TRUE):\npdbs/3GMT.pdb.gz exists. Skipping download\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in get.pdb(hits$pdb.id, path = \"pdbs\", split = TRUE, gzip = TRUE):\npdbs/4PZL.pdb.gz exists. Skipping download\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n  |                                                                            \n  |                                                                      |   0%\n  |                                                                            \n  |====                                                                  |   5%\n  |                                                                            \n  |=======                                                               |  11%\n  |                                                                            \n  |===========                                                           |  16%\n  |                                                                            \n  |===============                                                       |  21%\n  |                                                                            \n  |==================                                                    |  26%\n  |                                                                            \n  |======================                                                |  32%\n  |                                                                            \n  |==========================                                            |  37%\n  |                                                                            \n  |=============================                                         |  42%\n  |                                                                            \n  |=================================                                     |  47%\n  |                                                                            \n  |=====================================                                 |  53%\n  |                                                                            \n  |=========================================                             |  58%\n  |                                                                            \n  |============================================                          |  63%\n  |                                                                            \n  |================================================                      |  68%\n  |                                                                            \n  |====================================================                  |  74%\n  |                                                                            \n  |=======================================================               |  79%\n  |                                                                            \n  |===========================================================           |  84%\n  |                                                                            \n  |===============================================================       |  89%\n  |                                                                            \n  |==================================================================    |  95%\n  |                                                                            \n  |======================================================================| 100%\n```\n\n\n:::\n:::\n\n\n\n##Align and Superimpose structures:\n\n\n::: {.cell}\n\n```{.r .cell-code}\npdbs <- pdbaln(files, fit = TRUE, exefile=\"msa\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nReading PDB files:\npdbs/split_chain/1AKE_A.pdb\npdbs/split_chain/8BQF_A.pdb\npdbs/split_chain/4X8M_A.pdb\npdbs/split_chain/6S36_A.pdb\npdbs/split_chain/8Q2B_A.pdb\npdbs/split_chain/8RJ9_A.pdb\npdbs/split_chain/6RZE_A.pdb\npdbs/split_chain/4X8H_A.pdb\npdbs/split_chain/3HPR_A.pdb\npdbs/split_chain/1E4V_A.pdb\npdbs/split_chain/5EJE_A.pdb\npdbs/split_chain/1E4Y_A.pdb\npdbs/split_chain/3X2S_A.pdb\npdbs/split_chain/6HAP_A.pdb\npdbs/split_chain/6HAM_A.pdb\npdbs/split_chain/4K46_A.pdb\npdbs/split_chain/4NP6_A.pdb\npdbs/split_chain/3GMT_A.pdb\npdbs/split_chain/4PZL_A.pdb\n   PDB has ALT records, taking A only, rm.alt=TRUE\n.   PDB has ALT records, taking A only, rm.alt=TRUE\n..   PDB has ALT records, taking A only, rm.alt=TRUE\n.   PDB has ALT records, taking A only, rm.alt=TRUE\n.   PDB has ALT records, taking A only, rm.alt=TRUE\n.   PDB has ALT records, taking A only, rm.alt=TRUE\n..   PDB has ALT records, taking A only, rm.alt=TRUE\n..   PDB has ALT records, taking A only, rm.alt=TRUE\n....   PDB has ALT records, taking A only, rm.alt=TRUE\n.   PDB has ALT records, taking A only, rm.alt=TRUE\n....\n\nExtracting sequences\n\npdb/seq: 1   name: pdbs/split_chain/1AKE_A.pdb \n   PDB has ALT records, taking A only, rm.alt=TRUE\npdb/seq: 2   name: pdbs/split_chain/8BQF_A.pdb \n   PDB has ALT records, taking A only, rm.alt=TRUE\npdb/seq: 3   name: pdbs/split_chain/4X8M_A.pdb \npdb/seq: 4   name: pdbs/split_chain/6S36_A.pdb \n   PDB has ALT records, taking A only, rm.alt=TRUE\npdb/seq: 5   name: pdbs/split_chain/8Q2B_A.pdb \n   PDB has ALT records, taking A only, rm.alt=TRUE\npdb/seq: 6   name: pdbs/split_chain/8RJ9_A.pdb \n   PDB has ALT records, taking A only, rm.alt=TRUE\npdb/seq: 7   name: pdbs/split_chain/6RZE_A.pdb \n   PDB has ALT records, taking A only, rm.alt=TRUE\npdb/seq: 8   name: pdbs/split_chain/4X8H_A.pdb \npdb/seq: 9   name: pdbs/split_chain/3HPR_A.pdb \n   PDB has ALT records, taking A only, rm.alt=TRUE\npdb/seq: 10   name: pdbs/split_chain/1E4V_A.pdb \npdb/seq: 11   name: pdbs/split_chain/5EJE_A.pdb \n   PDB has ALT records, taking A only, rm.alt=TRUE\npdb/seq: 12   name: pdbs/split_chain/1E4Y_A.pdb \npdb/seq: 13   name: pdbs/split_chain/3X2S_A.pdb \npdb/seq: 14   name: pdbs/split_chain/6HAP_A.pdb \npdb/seq: 15   name: pdbs/split_chain/6HAM_A.pdb \n   PDB has ALT records, taking A only, rm.alt=TRUE\npdb/seq: 16   name: pdbs/split_chain/4K46_A.pdb \n   PDB has ALT records, taking A only, rm.alt=TRUE\npdb/seq: 17   name: pdbs/split_chain/4NP6_A.pdb \npdb/seq: 18   name: pdbs/split_chain/3GMT_A.pdb \npdb/seq: 19   name: pdbs/split_chain/4PZL_A.pdb \n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nids <- basename.pdb(pdbs$id)\n#plot(pdbs, labels=ids)\n\n#commenting out, as R will not render this figure. It is added here as a screenshot.\n```\n:::\n\n\n\n![pdbs plot](plot.png)\n\n##Annotate PDB Structures\n\n\n::: {.cell}\n\n```{.r .cell-code}\nanno <- pdb.annotate(ids)\nunique(anno$source)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"Escherichia coli\"                                \n[2] \"Escherichia coli K-12\"                           \n[3] \"Escherichia coli O139:H28 str. E24377A\"          \n[4] \"Escherichia coli str. K-12 substr. MDS42\"        \n[5] \"Photobacterium profundum\"                        \n[6] \"Vibrio cholerae O1 biovar El Tor str. N16961\"    \n[7] \"Burkholderia pseudomallei 1710b\"                 \n[8] \"Francisella tularensis subsp. tularensis SCHU S4\"\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nanno\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       structureId chainId macromoleculeType chainLength experimentalTechnique\n1AKE_A        1AKE       A           Protein         214                 X-ray\n8BQF_A        8BQF       A           Protein         234                 X-ray\n4X8M_A        4X8M       A           Protein         214                 X-ray\n6S36_A        6S36       A           Protein         214                 X-ray\n8Q2B_A        8Q2B       A           Protein         214                 X-ray\n8RJ9_A        8RJ9       A           Protein         214                 X-ray\n6RZE_A        6RZE       A           Protein         214                 X-ray\n4X8H_A        4X8H       A           Protein         214                 X-ray\n3HPR_A        3HPR       A           Protein         214                 X-ray\n1E4V_A        1E4V       A           Protein         214                 X-ray\n5EJE_A        5EJE       A           Protein         214                 X-ray\n1E4Y_A        1E4Y       A           Protein         214                 X-ray\n3X2S_A        3X2S       A           Protein         214                 X-ray\n6HAP_A        6HAP       A           Protein         214                 X-ray\n6HAM_A        6HAM       A           Protein         214                 X-ray\n4K46_A        4K46       A           Protein         214                 X-ray\n4NP6_A        4NP6       A           Protein         217                 X-ray\n3GMT_A        3GMT       A           Protein         230                 X-ray\n4PZL_A        4PZL       A           Protein         242                 X-ray\n       resolution       scopDomain                                        pfam\n1AKE_A      2.000 Adenylate kinase Adenylate kinase, active site lid (ADK_lid)\n8BQF_A      2.050             <NA> Adenylate kinase, active site lid (ADK_lid)\n4X8M_A      2.600             <NA>                      Adenylate kinase (ADK)\n6S36_A      1.600             <NA>                      Adenylate kinase (ADK)\n8Q2B_A      1.760             <NA> Adenylate kinase, active site lid (ADK_lid)\n8RJ9_A      1.590             <NA>                      Adenylate kinase (ADK)\n6RZE_A      1.690             <NA>                      Adenylate kinase (ADK)\n4X8H_A      2.500             <NA> Adenylate kinase, active site lid (ADK_lid)\n3HPR_A      2.000             <NA>                      Adenylate kinase (ADK)\n1E4V_A      1.850 Adenylate kinase                      Adenylate kinase (ADK)\n5EJE_A      1.900             <NA>                      Adenylate kinase (ADK)\n1E4Y_A      1.850 Adenylate kinase Adenylate kinase, active site lid (ADK_lid)\n3X2S_A      2.800             <NA>                      Adenylate kinase (ADK)\n6HAP_A      2.700             <NA> Adenylate kinase, active site lid (ADK_lid)\n6HAM_A      2.550             <NA>                      Adenylate kinase (ADK)\n4K46_A      2.010             <NA> Adenylate kinase, active site lid (ADK_lid)\n4NP6_A      2.004             <NA>                      Adenylate kinase (ADK)\n3GMT_A      2.100             <NA>                      Adenylate kinase (ADK)\n4PZL_A      2.100             <NA>                      Adenylate kinase (ADK)\n               ligandId\n1AKE_A              AP5\n8BQF_A              AP5\n4X8M_A             <NA>\n6S36_A CL (3),NA,MG (2)\n8Q2B_A      AP5,SO4,MPO\n8RJ9_A          ADP (2)\n6RZE_A    NA (3),CL (2)\n4X8H_A             <NA>\n3HPR_A              AP5\n1E4V_A              AP5\n5EJE_A           AP5,CO\n1E4Y_A              AP5\n3X2S_A   JPY (2),AP5,MG\n6HAP_A              AP5\n6HAM_A              AP5\n4K46_A      ADP,AMP,PO4\n4NP6_A             <NA>\n3GMT_A          SO4 (2)\n4PZL_A       CA,FMT,GOL\n                                                                              ligandName\n1AKE_A                                                  BIS(ADENOSINE)-5'-PENTAPHOSPHATE\n8BQF_A                                                  BIS(ADENOSINE)-5'-PENTAPHOSPHATE\n4X8M_A                                                                              <NA>\n6S36_A                                     CHLORIDE ION (3),SODIUM ION,MAGNESIUM ION (2)\n8Q2B_A BIS(ADENOSINE)-5'-PENTAPHOSPHATE,SULFATE ION,3[N-MORPHOLINO]PROPANE SULFONIC ACID\n8RJ9_A                                                      ADENOSINE-5'-DIPHOSPHATE (2)\n6RZE_A                                                   SODIUM ION (3),CHLORIDE ION (2)\n4X8H_A                                                                              <NA>\n3HPR_A                                                  BIS(ADENOSINE)-5'-PENTAPHOSPHATE\n1E4V_A                                                  BIS(ADENOSINE)-5'-PENTAPHOSPHATE\n5EJE_A                                  BIS(ADENOSINE)-5'-PENTAPHOSPHATE,COBALT (II) ION\n1E4Y_A                                                  BIS(ADENOSINE)-5'-PENTAPHOSPHATE\n3X2S_A  N-(pyren-1-ylmethyl)acetamide (2),BIS(ADENOSINE)-5'-PENTAPHOSPHATE,MAGNESIUM ION\n6HAP_A                                                  BIS(ADENOSINE)-5'-PENTAPHOSPHATE\n6HAM_A                                                  BIS(ADENOSINE)-5'-PENTAPHOSPHATE\n4K46_A                    ADENOSINE-5'-DIPHOSPHATE,ADENOSINE MONOPHOSPHATE,PHOSPHATE ION\n4NP6_A                                                                              <NA>\n3GMT_A                                                                   SULFATE ION (2)\n4PZL_A                                                  CALCIUM ION,FORMIC ACID,GLYCEROL\n                                                 source\n1AKE_A                                 Escherichia coli\n8BQF_A                                 Escherichia coli\n4X8M_A                                 Escherichia coli\n6S36_A                                 Escherichia coli\n8Q2B_A                                 Escherichia coli\n8RJ9_A                                 Escherichia coli\n6RZE_A                                 Escherichia coli\n4X8H_A                                 Escherichia coli\n3HPR_A                            Escherichia coli K-12\n1E4V_A                                 Escherichia coli\n5EJE_A           Escherichia coli O139:H28 str. E24377A\n1E4Y_A                                 Escherichia coli\n3X2S_A         Escherichia coli str. K-12 substr. MDS42\n6HAP_A           Escherichia coli O139:H28 str. E24377A\n6HAM_A                            Escherichia coli K-12\n4K46_A                         Photobacterium profundum\n4NP6_A     Vibrio cholerae O1 biovar El Tor str. N16961\n3GMT_A                  Burkholderia pseudomallei 1710b\n4PZL_A Francisella tularensis subsp. tularensis SCHU S4\n                                                                                                                                                                     structureTitle\n1AKE_A STRUCTURE OF THE COMPLEX BETWEEN ADENYLATE KINASE FROM ESCHERICHIA COLI AND THE INHIBITOR AP5A REFINED AT 1.9 ANGSTROMS RESOLUTION: A MODEL FOR A CATALYTIC TRANSITION STATE\n8BQF_A                                                                                                                                                Adenylate Kinase L107I MUTANT\n4X8M_A                                                                                                                   Crystal structure of E. coli Adenylate kinase Y171W mutant\n6S36_A                                                                                                                   Crystal structure of E. coli Adenylate kinase R119K mutant\n8Q2B_A                                              E. coli Adenylate Kinase variant D158A (AK D158A) showing significant changes to the stacking of catalytic arginine side chains\n8RJ9_A                                                        E. coli adenylate kinase Asp84Ala variant in complex with two ADP molecules as a result of enzymatic AP4A hydrolysis.\n6RZE_A                                                                                                                   Crystal structure of E. coli Adenylate kinase R119A mutant\n4X8H_A                                                                                                                   Crystal structure of E. coli Adenylate kinase P177A mutant\n3HPR_A                                                                                               Crystal structure of V148G adenylate kinase from E. coli, in complex with Ap5A\n1E4V_A                                                                                                       Mutant G10V of adenylate kinase from E. coli, modified in the Gly-loop\n5EJE_A                                                                                  Crystal structure of E. coli Adenylate kinase G56C/T163C double mutant in complex with Ap5a\n1E4Y_A                                                                                                        Mutant P9L of adenylate kinase from E. coli, modified in the Gly-loop\n3X2S_A                                                                                                                      Crystal structure of pyrene-conjugated adenylate kinase\n6HAP_A                                                                                                                                                             Adenylate kinase\n6HAM_A                                                                                                                                                             Adenylate kinase\n4K46_A                                                                                                          Crystal Structure of Adenylate Kinase from Photobacterium profundum\n4NP6_A                                                                                                   Crystal Structure of Adenylate Kinase from Vibrio cholerae O1 biovar eltor\n3GMT_A                                                                                                         Crystal structure of adenylate kinase from burkholderia pseudomallei\n4PZL_A                                                                              The crystal structure of adenylate kinase from Francisella tularensis subsp. tularensis SCHU S4\n                                                     citation rObserved   rFree\n1AKE_A                 Muller, C.W., et al. J Mol Biol (1992)   0.19600      NA\n8BQF_A   Scheerer, D., et al. Proc Natl Acad Sci U S A (2023)   0.22073 0.25789\n4X8M_A                Kovermann, M., et al. Nat Commun (2015)   0.24910 0.30890\n6S36_A                  Rogne, P., et al. Biochemistry (2019)   0.16320 0.23560\n8Q2B_A                Nam, K., et al. J Chem Inf Model (2024)   0.18320 0.22440\n8RJ9_A                         Nam, K., et al. Sci Adv (2024)   0.15190 0.20290\n6RZE_A                  Rogne, P., et al. Biochemistry (2019)   0.18650 0.23500\n4X8H_A                Kovermann, M., et al. Nat Commun (2015)   0.19610 0.28950\n3HPR_A  Schrank, T.P., et al. Proc Natl Acad Sci U S A (2009)   0.21000 0.24320\n1E4V_A                   Muller, C.W., et al. Proteins (1993)   0.19600      NA\n5EJE_A  Kovermann, M., et al. Proc Natl Acad Sci U S A (2017)   0.18890 0.23580\n1E4Y_A                   Muller, C.W., et al. Proteins (1993)   0.17800      NA\n3X2S_A                Fujii, A., et al. Bioconjug Chem (2015)   0.20700 0.25600\n6HAP_A               Kantaev, R., et al. J Phys Chem B (2018)   0.22630 0.27760\n6HAM_A               Kantaev, R., et al. J Phys Chem B (2018)   0.20511 0.24325\n4K46_A                    Cho, Y.-J., et al. To be published    0.17000 0.22290\n4NP6_A                       Kim, Y., et al. To be published    0.18800 0.22200\n3GMT_A Buchko, G.W., et al. Biochem Biophys Res Commun (2010)   0.23800 0.29500\n4PZL_A                       Tan, K., et al. To be published    0.19360 0.23680\n         rWork spaceGroup\n1AKE_A 0.19600  P 21 2 21\n8BQF_A 0.21882  P 2 21 21\n4X8M_A 0.24630    C 1 2 1\n6S36_A 0.15940    C 1 2 1\n8Q2B_A 0.18100   P 1 21 1\n8RJ9_A 0.15010  P 21 21 2\n6RZE_A 0.18190    C 1 2 1\n4X8H_A 0.19140    C 1 2 1\n3HPR_A 0.20620  P 21 21 2\n1E4V_A 0.19600  P 21 2 21\n5EJE_A 0.18630  P 21 2 21\n1E4Y_A 0.17800   P 1 21 1\n3X2S_A 0.20700 P 21 21 21\n6HAP_A 0.22370    I 2 2 2\n6HAM_A 0.20311       P 43\n4K46_A 0.16730 P 21 21 21\n4NP6_A 0.18600       P 43\n3GMT_A 0.23500   P 1 21 1\n4PZL_A 0.19130       P 32\n```\n\n\n:::\n:::\n\n\n\n##Perform PCA\n\n\n::: {.cell}\n\n```{.r .cell-code}\npc.xray <- pca(pdbs)\nplot(pc.xray)\n```\n\n::: {.cell-output-display}\n![](JCW_110124_bioinfo_Class10_files/figure-pdf/unnamed-chunk-29-1.pdf){fig-pos='H'}\n:::\n:::\n\n\n##Calculate RMSD and show structure-based clustering\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrd <- rmsd(pdbs)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in rmsd(pdbs): No indices provided, using the 199 non NA positions\n```\n\n\n:::\n\n```{.r .cell-code}\nhc.rd <- hclust(dist(rd))\ngrps.rd <- cutree(hc.rd, k=3)\n\nplot(pc.xray, 1:2, col=\"grey50\", bg=grps.rd, pch=21, cex=1)\n```\n\n::: {.cell-output-display}\n![](JCW_110124_bioinfo_Class10_files/figure-pdf/unnamed-chunk-30-1.pdf){fig-pos='H'}\n:::\n:::\n",
    "supporting": [
      "JCW_110124_bioinfo_Class10_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": null,
    "postProcess": false
  }
}