theme: jekyll-theme-minimal
logo: https://cdn2.iconfinder.com/data/icons/alien-ufo-invader-invasion/373/alien-ufo-invader-16-1024.png
title: Janie Changberg's BioInfo Work
subtitle: I'll fold you like Alpha Fold's proteins
