{
  "hash": "507b6c1ddf81aecd7c09f126c9323db8",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Halloween Mini Project 103024\"\nauthor: \"Janie Changberg (PID: A69037446)\"\nformat: pdf\n---\n\n::: {.cell}\n\n```{.r .cell-code}\ncandy_file <- \"candy-data.csv\"\ncandy = read.csv(candy_file,row.names=1)\nhead(candy)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n             chocolate fruity caramel peanutyalmondy nougat crispedricewafer\n100 Grand            1      0       1              0      0                1\n3 Musketeers         1      0       0              0      1                0\nOne dime             0      0       0              0      0                0\nOne quarter          0      0       0              0      0                0\nAir Heads            0      1       0              0      0                0\nAlmond Joy           1      0       0              1      0                0\n             hard bar pluribus sugarpercent pricepercent winpercent\n100 Grand       0   1        0        0.732        0.860   66.97173\n3 Musketeers    0   1        0        0.604        0.511   67.60294\nOne dime        0   0        0        0.011        0.116   32.26109\nOne quarter     0   0        0        0.011        0.511   46.11650\nAir Heads       0   0        0        0.906        0.511   52.34146\nAlmond Joy      0   1        0        0.465        0.767   50.34755\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\ndim(candy)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 85 12\n```\n\n\n:::\n\n```{.r .cell-code}\nnrow(candy)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 85\n```\n\n\n:::\n\n```{.r .cell-code}\nsum(candy$fruity)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 38\n```\n\n\n:::\n:::\n\n\n\n##Q1. How many different candy types are in this dataset?\n\n> 85 different candies\n\n##Q2. How many fruity candy types are in the dataset?\n\n> 38 types of fruity candy\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncandy[\"Twix\", ]$winpercent\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 81.64291\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\ncandy[\"Reese's Peanut Butter cup\",]$winpercent\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 84.18029\n```\n\n\n:::\n\n```{.r .cell-code}\ncandy[\"Kit Kat\",]$winpercent\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 76.7686\n```\n\n\n:::\n\n```{.r .cell-code}\ncandy[\"Tootsie Roll Snack Bars\",]$winpercent\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 49.6535\n```\n\n\n:::\n:::\n\n\n\n##Q3. What is your favorite candy in the dataset and what is its `winpercent` value?\n\n> Reese's Peanut Butter Cups, 84.18029.\n\n##Q4. What is the `winpercent` value for “Kit Kat”?\n\n> 76.768\n\n##Q5. What is the `winpercent` value for “Tootsie Roll Snack Bars”? \\>49.6535\n\nInstalled Skimr:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(\"skimr\")\nskim(candy)\n```\n\n::: {.cell-output-display}\n\nTable: Data summary\n\n|                         |      |\n|:------------------------|:-----|\n|Name                     |candy |\n|Number of rows           |85    |\n|Number of columns        |12    |\n|_______________________  |      |\n|Column type frequency:   |      |\n|numeric                  |12    |\n|________________________ |      |\n|Group variables          |None  |\n\n\n**Variable type: numeric**\n\n|skim_variable    | n_missing| complete_rate|  mean|    sd|    p0|   p25|   p50|   p75|  p100|hist  |\n|:----------------|---------:|-------------:|-----:|-----:|-----:|-----:|-----:|-----:|-----:|:-----|\n|chocolate        |         0|             1|  0.44|  0.50|  0.00|  0.00|  0.00|  1.00|  1.00|▇▁▁▁▆ |\n|fruity           |         0|             1|  0.45|  0.50|  0.00|  0.00|  0.00|  1.00|  1.00|▇▁▁▁▆ |\n|caramel          |         0|             1|  0.16|  0.37|  0.00|  0.00|  0.00|  0.00|  1.00|▇▁▁▁▂ |\n|peanutyalmondy   |         0|             1|  0.16|  0.37|  0.00|  0.00|  0.00|  0.00|  1.00|▇▁▁▁▂ |\n|nougat           |         0|             1|  0.08|  0.28|  0.00|  0.00|  0.00|  0.00|  1.00|▇▁▁▁▁ |\n|crispedricewafer |         0|             1|  0.08|  0.28|  0.00|  0.00|  0.00|  0.00|  1.00|▇▁▁▁▁ |\n|hard             |         0|             1|  0.18|  0.38|  0.00|  0.00|  0.00|  0.00|  1.00|▇▁▁▁▂ |\n|bar              |         0|             1|  0.25|  0.43|  0.00|  0.00|  0.00|  0.00|  1.00|▇▁▁▁▂ |\n|pluribus         |         0|             1|  0.52|  0.50|  0.00|  0.00|  1.00|  1.00|  1.00|▇▁▁▁▇ |\n|sugarpercent     |         0|             1|  0.48|  0.28|  0.01|  0.22|  0.47|  0.73|  0.99|▇▇▇▇▆ |\n|pricepercent     |         0|             1|  0.47|  0.29|  0.01|  0.26|  0.47|  0.65|  0.98|▇▇▇▇▆ |\n|winpercent       |         0|             1| 50.32| 14.71| 22.45| 39.14| 47.83| 59.86| 84.18|▃▇▆▅▂ |\n\n\n:::\n:::\n\n\n\n##Q6. Is there any variable/column that looks to be on a different scale to the majority of the other columns in the dataset?\n\n>The three \"percent\" values (sugarpercent, pricepercent, winpercent) are continuous variables vs binary values (the other columns are 0 or 1) for the p0-p100 values.\n\n\n##Q7. What do you think a zero and one represent for the candy$chocolate column?\n\n>They likely represent a \"yes/no\" answer to whether that particular candy contains that element. \n\n##Q8. Plot a histogram of `winpercent` values\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(ggplot2)\n\nggplot(candy, aes(x=winpercent))+\n  geom_histogram(binwidth=5, color=(\"black\"))\n```\n\n::: {.cell-output-display}\n![](Halloween_Mini_Project_103024_files/figure-pdf/unnamed-chunk-6-1.pdf){fig-pos='H'}\n:::\n:::\n\n\n\n##Q9. Is the distribution of `winpercent` values symmetrical?\n\n>No, the values are skewed to the right.\n\n##Q10. Is the center of the distribution above or below 50%?\n\n>The center of the distribution is below 50%.\n\n##Q11. On average is chocolate candy higher or lower ranked than fruit candy?\n\n\n::: {.cell}\n\n```{.r .cell-code}\nchoc_mean <- mean(candy$winpercent[as.logical(candy$chocolate)], na.rm=TRUE)\nfruit_mean <- mean(candy$winpercent[as.logical(candy$fruity)], na.rm=TRUE)\n\nchoc_mean\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 60.92153\n```\n\n\n:::\n\n```{.r .cell-code}\nfruit_mean\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 44.11974\n```\n\n\n:::\n:::\n\n\n>Chocolate candy is ranked higher than fruit candy (60.92% win vs 44.12% win)\n\n##Q12. Is this difference statistically significant?\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nttest_chocvsfruit <- t.test(candy$winpercent[as.logical(candy$chocolate)], na.rm=TRUE,candy$winpercent[as.logical(candy$fruity)], na.rm=TRUE)\n\nttest_chocvsfruit\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tWelch Two Sample t-test\n\ndata:  candy$winpercent[as.logical(candy$chocolate)] and candy$winpercent[as.logical(candy$fruity)]\nt = 6.2582, df = 68.882, p-value = 2.871e-08\nalternative hypothesis: true difference in means is not equal to 0\n95 percent confidence interval:\n 11.44563 22.15795\nsample estimates:\nmean of x mean of y \n 60.92153  44.11974 \n```\n\n\n:::\n:::\n\n\n>Yes, this difference is statistically significant, p-val=2.871e-08\n  \n##Q13. what are the five least liked candy types in this set?\n\n\n::: {.cell}\n\n```{.r .cell-code}\ninds <- order(candy$winpercent)\nhead(candy[inds,])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                   chocolate fruity caramel peanutyalmondy nougat\nNik L Nip                  0      1       0              0      0\nBoston Baked Beans         0      0       0              1      0\nChiclets                   0      1       0              0      0\nSuper Bubble               0      1       0              0      0\nJawbusters                 0      1       0              0      0\nRoot Beer Barrels          0      0       0              0      0\n                   crispedricewafer hard bar pluribus sugarpercent pricepercent\nNik L Nip                         0    0   0        1        0.197        0.976\nBoston Baked Beans                0    0   0        1        0.313        0.511\nChiclets                          0    0   0        1        0.046        0.325\nSuper Bubble                      0    0   0        0        0.162        0.116\nJawbusters                        0    1   0        1        0.093        0.511\nRoot Beer Barrels                 0    1   0        1        0.732        0.069\n                   winpercent\nNik L Nip            22.44534\nBoston Baked Beans   23.41782\nChiclets             24.52499\nSuper Bubble         27.30386\nJawbusters           28.12744\nRoot Beer Barrels    29.70369\n```\n\n\n:::\n:::\n\n\n>Nik L Nip, Boston Baked Beans, Chiclets, Super Bubble, Jawbusters\n    \n\n##Q14. What are the top 5 all time favorite candy types out of this set?\n\n\n::: {.cell}\n\n```{.r .cell-code}\ninds2 <- order(candy$winpercent)\ntail(candy[inds,])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                          chocolate fruity caramel peanutyalmondy nougat\nReese's pieces                    1      0       0              1      0\nSnickers                          1      0       1              1      1\nKit Kat                           1      0       0              0      0\nTwix                              1      0       1              0      0\nReese's Miniatures                1      0       0              1      0\nReese's Peanut Butter cup         1      0       0              1      0\n                          crispedricewafer hard bar pluribus sugarpercent\nReese's pieces                           0    0   0        1        0.406\nSnickers                                 0    0   1        0        0.546\nKit Kat                                  1    0   1        0        0.313\nTwix                                     1    0   1        0        0.546\nReese's Miniatures                       0    0   0        0        0.034\nReese's Peanut Butter cup                0    0   0        0        0.720\n                          pricepercent winpercent\nReese's pieces                   0.651   73.43499\nSnickers                         0.651   76.67378\nKit Kat                          0.511   76.76860\nTwix                             0.906   81.64291\nReese's Miniatures               0.279   81.86626\nReese's Peanut Butter cup        0.651   84.18029\n```\n\n\n:::\n:::\n\n\n> Reese's pieces, Snickers, Kit Kat, Twix, Reese's Miniatures\n\n##Q15. Make a first barplot of candy ranking based on winpercent values.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nq15plot<- ggplot(candy)+\n  aes(winpercent, rownames(candy))+\n  geom_col()\nq15plot\n```\n\n::: {.cell-output-display}\n![](Halloween_Mini_Project_103024_files/figure-pdf/unnamed-chunk-11-1.pdf){fig-pos='H'}\n:::\n:::\n\n\n\n##Q16. This is quite ugly, use the reorder() function to get the bars sorted by winpercent?\n\n\n::: {.cell}\n\n```{.r .cell-code}\nq16plot <- ggplot(candy)+\n  aes(winpercent, reorder(rownames(candy),winpercent))+\n  geom_col()\nq16plot\n```\n\n::: {.cell-output-display}\n![](Halloween_Mini_Project_103024_files/figure-pdf/unnamed-chunk-12-1.pdf){fig-pos='H'}\n:::\n:::\n\n\n##Let's make it purdy\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmy_cols=rep(\"orange\", nrow(candy))\nmy_cols[as.logical(candy$chocolate)] = \"brown\"\nmy_cols[as.logical(candy$bar)] = \"blue\"\nmy_cols[as.logical(candy$fruity)] = \"darkgreen\"\n\nbeautify <- ggplot(candy) + \n  aes(winpercent, reorder(rownames(candy),winpercent)) +\n  geom_col(fill=my_cols) \nbeautify\n```\n\n::: {.cell-output-display}\n![](Halloween_Mini_Project_103024_files/figure-pdf/unnamed-chunk-13-1.pdf){fig-pos='H'}\n:::\n:::\n\n\n##Q17. What is the worst ranked chocolate candy?\n>The worst ranked chocolate candy is sixlets (as an aside, I have never heard of these).\n\n##Q18. What is the best ranked fruity candy?\n>The best ranked fruity candy is starbursts.\n\n##What about value for money? What is the the best candy for the least money? \n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(ggrepel)\n\n\nbestval <- ggplot(candy) +\n  aes(winpercent, pricepercent, label=rownames(candy)) +\n  geom_point(col=my_cols) + \n  geom_text_repel(col=my_cols, size=3.3, max.overlaps = 5)\nbestval\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: ggrepel: 65 unlabeled data points (too many overlaps). Consider\nincreasing max.overlaps\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](Halloween_Mini_Project_103024_files/figure-pdf/unnamed-chunk-14-1.pdf){fig-pos='H'}\n:::\n:::\n\n\n\n##Q19. Which candy type is the highest ranked in terms of winpercent for the least money - i.e. offers the most bang for your buck?\n\n> Reese's Miniatures are around the 25th percentile in price, and is the second most popular candy.\n\n##Q20. What are the top 5 most expensive candy types in the dataset and of these which is the least popular?\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmy_cols=rep(\"orange\", nrow(candy))\nmy_cols[as.logical(candy$chocolate)] = \"brown\"\nmy_cols[as.logical(candy$bar)] = \"blue\"\nmy_cols[as.logical(candy$fruity)] = \"darkgreen\"\n\nq20beautify <- ggplot(candy) + \n  aes(pricepercent, reorder(rownames(candy),pricepercent)) +\n  geom_col(fill=my_cols) \nq20beautify\n```\n\n::: {.cell-output-display}\n![](Halloween_Mini_Project_103024_files/figure-pdf/unnamed-chunk-15-1.pdf){fig-pos='H'}\n:::\n:::\n\n\n\n>Nik L Nip, Nestle Smarties, Ring Pop, Mr. Good bar, and Hershey's Special Dark. The least popular of these is Nik L Nip.\n\n##Q21. Make a barplot again with geom_col() this time using pricepercent and then improve this step by step, first ordering the x-axis by value and finally making a so called “dot chat” or “lollipop” chart by swapping geom_col() for geom_point() + geom_segment().\n\n>see plot generated for Q20 for barplot based on pricepercent. Below is the called for improvement:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlollipoppriceplot <- ggplot(candy) +\n  aes(pricepercent, reorder(rownames(candy), pricepercent)) +\n  geom_segment(aes(yend = reorder(rownames(candy), pricepercent), xend = 0), col=\"gray40\") +\n  geom_point()\nlollipoppriceplot\n```\n\n::: {.cell-output-display}\n![](Halloween_Mini_Project_103024_files/figure-pdf/unnamed-chunk-16-1.pdf){fig-pos='H'}\n:::\n:::\n\n\n\n##Exploring the Correlation Structure\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(corrplot)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\ncorrplot 0.95 loaded\n```\n\n\n:::\n\n```{.r .cell-code}\ncorstruct <- cor(candy)\ncorrplot(corstruct)\n```\n\n::: {.cell-output-display}\n![](Halloween_Mini_Project_103024_files/figure-pdf/unnamed-chunk-17-1.pdf){fig-pos='H'}\n:::\n:::\n\n\n##Q22. Examining this plot what two variables are anti-correlated (i.e. have minus values)?\n\n> Chocolate and Fruity, bar and pluribus.\n\n##Q23. Similarly, what two variables are most positively correlated?\n\n> Chocolate & bar, and Chocolate & winpercent\n\n##Principal Component Analysis\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npca <- prcomp(candy, scale=TRUE)\nsummary(pca)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nImportance of components:\n                          PC1    PC2    PC3     PC4    PC5     PC6     PC7\nStandard deviation     2.0788 1.1378 1.1092 1.07533 0.9518 0.81923 0.81530\nProportion of Variance 0.3601 0.1079 0.1025 0.09636 0.0755 0.05593 0.05539\nCumulative Proportion  0.3601 0.4680 0.5705 0.66688 0.7424 0.79830 0.85369\n                           PC8     PC9    PC10    PC11    PC12\nStandard deviation     0.74530 0.67824 0.62349 0.43974 0.39760\nProportion of Variance 0.04629 0.03833 0.03239 0.01611 0.01317\nCumulative Proportion  0.89998 0.93832 0.97071 0.98683 1.00000\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(pca$x[,1:2], col=my_cols, pch=18)\n```\n\n::: {.cell-output-display}\n![](Halloween_Mini_Project_103024_files/figure-pdf/unnamed-chunk-19-1.pdf){fig-pos='H'}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# Make a new data-frame with our PCA results and candy data\nmy_data <- cbind(candy, pca$x[,1:3])\n```\n:::\n\n\n\n##Make nice with GGPlot:\n\n\n::: {.cell}\n\n```{.r .cell-code}\np <- ggplot(my_data) + \n        aes(x=PC1, y=PC2, \n            size=winpercent/100,  \n            text=rownames(my_data),\n            label=rownames(my_data)) +\n        geom_point(col=my_cols)\n\np\n```\n\n::: {.cell-output-display}\n![](Halloween_Mini_Project_103024_files/figure-pdf/unnamed-chunk-21-1.pdf){fig-pos='H'}\n:::\n:::\n\n\n##Use GGRepel to make labels that don't overlap\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(ggrepel)\n\np + geom_text_repel(size=3.3, col=my_cols, max.overlaps = 7)  + \n  theme(legend.position = \"none\") +\n  labs(title=\"Halloween Candy PCA Space\",\n       subtitle=\"Colored by type: chocolate bar (dark brown), chocolate other (light brown), fruity (red), other (black)\",\n       caption=\"Data from 538\")\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: ggrepel: 59 unlabeled data points (too many overlaps). Consider\nincreasing max.overlaps\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](Halloween_Mini_Project_103024_files/figure-pdf/unnamed-chunk-22-1.pdf){fig-pos='H'}\n:::\n:::\n\n\n\n##Still weird, use plotly\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(plotly)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n\nAttaching package: 'plotly'\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nThe following object is masked from 'package:ggplot2':\n\n    last_plot\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nThe following object is masked from 'package:stats':\n\n    filter\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nThe following object is masked from 'package:graphics':\n\n    layout\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nggplotly(p)\n```\n\n::: {.cell-output-display}\n![](Halloween_Mini_Project_103024_files/figure-pdf/unnamed-chunk-24-1.pdf){fig-pos='H'}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\npar(mar=c(8,4,2,2))\nbarplot(pca$rotation[,1], las=2, ylab=\"PC1 Contribution\")\n```\n\n::: {.cell-output-display}\n![](Halloween_Mini_Project_103024_files/figure-pdf/unnamed-chunk-25-1.pdf){fig-pos='H'}\n:::\n:::\n\n\n\n##Q24. What original variables are picked up strongly by PC1 in the positive direction? Do these make sense to you?\n\n> Fruity and Pluribus. Yes, fruity candy often is sold as multiples in a packet.",
    "supporting": [
      "Halloween_Mini_Project_103024_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": null,
    "postProcess": false
  }
}