{
  "hash": "7ec4d23e3cda76feb503266219f0cc46",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"JCW_111324_Class13_genomics lab\"\nauthor: \"Janie Chang-Weinberg (A69037446)\"\nformat: html\n---\n\n\n\nToday we will work with a dataset \"from a published RNA-seq experiment where airway smooth muscle cells were treated with dexamethasone, a synthetic glucocorticoid steroid with anti-inflammatory effects (Himes et al. 2014).\" (from lab worksheet).\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncounts <- read.csv(\"airway_scaledcounts.csv\", row.names=1)\nmetadata <- read.csv(\"airway_metadata.csv\")\n```\n:::\n\n\n\nlets have a look!\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhead(counts)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                SRR1039508 SRR1039509 SRR1039512 SRR1039513 SRR1039516\nENSG00000000003        723        486        904        445       1170\nENSG00000000005          0          0          0          0          0\nENSG00000000419        467        523        616        371        582\nENSG00000000457        347        258        364        237        318\nENSG00000000460         96         81         73         66        118\nENSG00000000938          0          0          1          0          2\n                SRR1039517 SRR1039520 SRR1039521\nENSG00000000003       1097        806        604\nENSG00000000005          0          0          0\nENSG00000000419        781        417        509\nENSG00000000457        447        330        324\nENSG00000000460         94        102         74\nENSG00000000938          0          0          0\n```\n\n\n:::\n:::\n\n\n\nNot particularly helpful, will have to look at metadata\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhead(metadata)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n          id     dex celltype     geo_id\n1 SRR1039508 control   N61311 GSM1275862\n2 SRR1039509 treated   N61311 GSM1275863\n3 SRR1039512 control  N052611 GSM1275866\n4 SRR1039513 treated  N052611 GSM1275867\n5 SRR1039516 control  N080611 GSM1275870\n6 SRR1039517 treated  N080611 GSM1275871\n```\n\n\n:::\n:::\n\n\n\nQ1. How many genes are in this dataset? \n\n\n::: {.cell}\n\n```{.r .cell-code}\nnrow(counts)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 38694\n```\n\n\n:::\n:::\n\n\n> There are 38,694 genes in this dataset\n\n\nQ2. How many ‘control’ cell lines do we have? \n\n\n::: {.cell}\n\n```{.r .cell-code}\nsum(metadata$dex == \"control\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 4\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\ntable(metadata$dex)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\ncontrol treated \n      4       4 \n```\n\n\n:::\n:::\n\n\n\n> There are 4 control cell lines.\n\nThe goal here is to compare \"control\" vs \"treated\" cells.\n\n1.) Let's split the `counts` into `control.counts` and `treated.counts`\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmetadata$id == colnames(counts)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\ncontrol.inds <- metadata$dex == \"control\"\ncontrol.inds\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1]  TRUE FALSE  TRUE FALSE  TRUE FALSE  TRUE FALSE\n```\n\n\n:::\n:::\n\n\n\nSyntax with df[ROWs, COLs]\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#This is to pull out the control columns\ncontrol.counts <- counts[,control.inds]\nhead(control.counts)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                SRR1039508 SRR1039512 SRR1039516 SRR1039520\nENSG00000000003        723        904       1170        806\nENSG00000000005          0          0          0          0\nENSG00000000419        467        616        582        417\nENSG00000000457        347        364        318        330\nENSG00000000460         96         73        118        102\nENSG00000000938          0          1          2          0\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\ntreated.inds <- metadata$dex == \"treated\"\ntreated.counts <- counts[,treated.inds]\nhead(treated.counts)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                SRR1039509 SRR1039513 SRR1039517 SRR1039521\nENSG00000000003        486        445       1097        604\nENSG00000000005          0          0          0          0\nENSG00000000419        523        371        781        509\nENSG00000000457        258        237        447        324\nENSG00000000460         81         66         94         74\nENSG00000000938          0          0          0          0\n```\n\n\n:::\n:::\n\n\n\n2. Let's calculate the mean counts per gene for \"control\" and \"treated\" - then we can compare these. Let's call it `control.mean` and `treated.mean`.\n\nI can use the `apply()` function to apply `mean()` over the rows or columns of any data.frame.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncontrol.mean <- apply(control.counts, 1, mean)\ntreated.mean <- apply(treated.counts, 1, mean)\n```\n:::\n\n\n\nPut these two together for ease of book-keeping \n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmeancounts <- data.frame(control.mean, treated.mean)\nplot(meancounts)\n```\n\n::: {.cell-output-display}\n![](JCW_111324_Class13_genomics-lab_files/figure-html/unnamed-chunk-12-1.png){width=672}\n:::\n:::\n\n\nThese data are heavily skewed. Let's transform it using logs. \n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(meancounts, log=\"xy\")\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in xy.coords(x, y, xlabel, ylabel, log): 15032 x values <= 0 omitted\nfrom logarithmic plot\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in xy.coords(x, y, xlabel, ylabel, log): 15281 y values <= 0 omitted\nfrom logarithmic plot\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](JCW_111324_Class13_genomics-lab_files/figure-html/unnamed-chunk-13-1.png){width=672}\n:::\n:::\n\n\n\n\nWe most often use `log2` transforms here because it makes the math easier\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlog2(10/10)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0\n```\n\n\n:::\n:::\n\n\n0= no change\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlog2(20/10)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1\n```\n\n\n:::\n:::\n\n\n1 = increase\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlog2(10/20)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] -1\n```\n\n\n:::\n:::\n\n\n-1 = decrease\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlog2(40/10)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 2\n```\n\n\n:::\n:::\n\n\n*log2 change of +2 is 4x increase (2 x 2)\n\nLet's calculate the Log2 fold-change of the drug and add it to our table, `meancounts`\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmeancounts$log2fc <- log2(meancounts$treated.mean/\n                          meancounts$control.mean)\nhead(meancounts)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                control.mean treated.mean      log2fc\nENSG00000000003       900.75       658.00 -0.45303916\nENSG00000000005         0.00         0.00         NaN\nENSG00000000419       520.50       546.00  0.06900279\nENSG00000000457       339.75       316.50 -0.10226805\nENSG00000000460        97.25        78.75 -0.30441833\nENSG00000000938         0.75         0.00        -Inf\n```\n\n\n:::\n:::\n\n\n\nFilter out all genes with zero counts in either control or treated:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nto.rm <- rowSums(meancounts[,1:2] == 0) > 0\nmycounts <- meancounts[!to.rm,]\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nnrow(mycounts)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 21817\n```\n\n\n:::\n\n```{.r .cell-code}\nhead(mycounts)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                control.mean treated.mean      log2fc\nENSG00000000003       900.75       658.00 -0.45303916\nENSG00000000419       520.50       546.00  0.06900279\nENSG00000000457       339.75       316.50 -0.10226805\nENSG00000000460        97.25        78.75 -0.30441833\nENSG00000000971      5219.00      6687.50  0.35769358\nENSG00000001036      2327.00      1785.75 -0.38194109\n```\n\n\n:::\n:::\n\n\nHow many \"down\" regulated genes do we have at the common log2 fold change values of -2?\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsum(mycounts$log2fc < -2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 367\n```\n\n\n:::\n:::\n\n\n> There are 367 \"down\" regulated genes with a log2FC of less than -2.\n\nHow many \"up\" at log2FC > +2?\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsum(mycounts$log2fc > +2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 250\n```\n\n\n:::\n:::\n\n\n> There are 250 \"up\" regulated genes with a log2FC of greater than +2.\n\nDo we trust these results? Is there anything missing?\n> There are no statistics! Give the people a p-value.\n\n## DESeq analysis\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(DESeq2)\n```\n:::\n\n\n\nDESeq, like many BioConductor packages, wants our input data in a very specific format. \n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#have to give the countData and the colData.The ~ indicates the design info is in the dex column of the data\ndds <- DESeqDataSetFromMatrix(countData = counts,\n                       colData = metadata,\n                       design = ~dex)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nconverting counts to integer mode\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in DESeqDataSet(se, design = design, ignoreRank): some variables in\ndesign formula are characters, converting to factors\n```\n\n\n:::\n:::\n\n\n\nThe main function of DESeq2 is called `DESeq()` and this will do much of the statistical analysis for us.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndds <- DESeq(dds)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nestimating size factors\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nestimating dispersions\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\ngene-wise dispersion estimates\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nmean-dispersion relationship\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nfinal dispersion estimates\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nfitting model and testing\n```\n\n\n:::\n\n```{.r .cell-code}\nres <- results(dds)\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nhead(res)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nlog2 fold change (MLE): dex treated vs control \nWald test p-value: dex treated vs control \nDataFrame with 6 rows and 6 columns\n                  baseMean log2FoldChange     lfcSE      stat    pvalue\n                 <numeric>      <numeric> <numeric> <numeric> <numeric>\nENSG00000000003 747.194195     -0.3507030  0.168246 -2.084470 0.0371175\nENSG00000000005   0.000000             NA        NA        NA        NA\nENSG00000000419 520.134160      0.2061078  0.101059  2.039475 0.0414026\nENSG00000000457 322.664844      0.0245269  0.145145  0.168982 0.8658106\nENSG00000000460  87.682625     -0.1471420  0.257007 -0.572521 0.5669691\nENSG00000000938   0.319167     -1.7322890  3.493601 -0.495846 0.6200029\n                     padj\n                <numeric>\nENSG00000000003  0.163035\nENSG00000000005        NA\nENSG00000000419  0.176032\nENSG00000000457  0.961694\nENSG00000000460  0.815849\nENSG00000000938        NA\n```\n\n\n:::\n:::\n\n\n\nA common overview figure plots the logFC s P-value\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(res$log2FoldChange, -log(res$padj))\n```\n\n::: {.cell-output-display}\n![](JCW_111324_Class13_genomics-lab_files/figure-html/unnamed-chunk-27-1.png){width=672}\n:::\n:::\n\n\n(the points that are at the top have a smaller p-value-- you transformed it w/ log, and then inverted it so the plot is oriented \"correctly\")\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(res$log2FoldChange, -log(res$padj))\nabline(v=c(-2,2), col=\"grey\")\nabline(h=-log(0.005), col=\"grey\")\n```\n\n::: {.cell-output-display}\n![](JCW_111324_Class13_genomics-lab_files/figure-html/unnamed-chunk-28-1.png){width=672}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nmycols <- rep(\"grey\", nrow(res))\nhead(mycols)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"grey\" \"grey\" \"grey\" \"grey\" \"grey\" \"grey\"\n```\n\n\n:::\n\n```{.r .cell-code}\nmycols[res$log2FoldChange > 2] <- \"red\"\nmycols[res$log2FoldChange < -2] <- \"red\"\nmycols[res$padj > 0.005] <- \"gray\"\n\nplot(res$log2FoldChange, -log(res$padj), col=mycols)\nabline(v=c(-2,2), col=\"gray\")\nabline(h=-log(0.005), col=\"gray\")\n```\n\n::: {.cell-output-display}\n![](JCW_111324_Class13_genomics-lab_files/figure-html/unnamed-chunk-29-1.png){width=672}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nwrite.csv(res, file=\"myresults.csv\")\n```\n:::\n\n\n\nLet's annotate things!\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(\"AnnotationDbi\")\nlibrary(\"org.Hs.eg.db\")\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\ncolumns(org.Hs.eg.db)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n [1] \"ACCNUM\"       \"ALIAS\"        \"ENSEMBL\"      \"ENSEMBLPROT\"  \"ENSEMBLTRANS\"\n [6] \"ENTREZID\"     \"ENZYME\"       \"EVIDENCE\"     \"EVIDENCEALL\"  \"GENENAME\"    \n[11] \"GENETYPE\"     \"GO\"           \"GOALL\"        \"IPI\"          \"MAP\"         \n[16] \"OMIM\"         \"ONTOLOGY\"     \"ONTOLOGYALL\"  \"PATH\"         \"PFAM\"        \n[21] \"PMID\"         \"PROSITE\"      \"REFSEQ\"       \"SYMBOL\"       \"UCSCKG\"      \n[26] \"UNIPROT\"     \n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nres$symbol <- mapIds(org.Hs.eg.db,\n                     keys=row.names(res), \n                     keytype=\"ENSEMBL\",        \n                     column=\"SYMBOL\",        \n                     multiVals=\"first\")\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n'select()' returned 1:many mapping between keys and columns\n```\n\n\n:::\n\n```{.r .cell-code}\nhead(res)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nlog2 fold change (MLE): dex treated vs control \nWald test p-value: dex treated vs control \nDataFrame with 6 rows and 7 columns\n                  baseMean log2FoldChange     lfcSE      stat    pvalue\n                 <numeric>      <numeric> <numeric> <numeric> <numeric>\nENSG00000000003 747.194195     -0.3507030  0.168246 -2.084470 0.0371175\nENSG00000000005   0.000000             NA        NA        NA        NA\nENSG00000000419 520.134160      0.2061078  0.101059  2.039475 0.0414026\nENSG00000000457 322.664844      0.0245269  0.145145  0.168982 0.8658106\nENSG00000000460  87.682625     -0.1471420  0.257007 -0.572521 0.5669691\nENSG00000000938   0.319167     -1.7322890  3.493601 -0.495846 0.6200029\n                     padj      symbol\n                <numeric> <character>\nENSG00000000003  0.163035      TSPAN6\nENSG00000000005        NA        TNMD\nENSG00000000419  0.176032        DPM1\nENSG00000000457  0.961694       SCYL3\nENSG00000000460  0.815849       FIRRM\nENSG00000000938        NA         FGR\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(pathview)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n##############################################################################\nPathview is an open source software package distributed under GNU General\nPublic License version 3 (GPLv3). Details of GPLv3 is available at\nhttp://www.gnu.org/licenses/gpl-3.0.html. Particullary, users are required to\nformally cite the original Pathview paper (not just mention it) in publications\nor products. For details, do citation(\"pathview\") within R.\n\nThe pathview downloads and uses KEGG data. Non-academic uses may require a KEGG\nlicense agreement (details at http://www.kegg.jp/kegg/legal.html).\n##############################################################################\n```\n\n\n:::\n\n```{.r .cell-code}\nlibrary(gage)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n\n```\n\n\n:::\n\n```{.r .cell-code}\nlibrary(gageData)\n\ndata(kegg.sets.hs)\n\n# Examine the first 2 pathways in this kegg set for humans\nhead(kegg.sets.hs, 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n$`hsa00232 Caffeine metabolism`\n[1] \"10\"   \"1544\" \"1548\" \"1549\" \"1553\" \"7498\" \"9\"   \n\n$`hsa00983 Drug metabolism - other enzymes`\n [1] \"10\"     \"1066\"   \"10720\"  \"10941\"  \"151531\" \"1548\"   \"1549\"   \"1551\"  \n [9] \"1553\"   \"1576\"   \"1577\"   \"1806\"   \"1807\"   \"1890\"   \"221223\" \"2990\"  \n[17] \"3251\"   \"3614\"   \"3615\"   \"3704\"   \"51733\"  \"54490\"  \"54575\"  \"54576\" \n[25] \"54577\"  \"54578\"  \"54579\"  \"54600\"  \"54657\"  \"54658\"  \"54659\"  \"54963\" \n[33] \"574537\" \"64816\"  \"7083\"   \"7084\"   \"7172\"   \"7363\"   \"7364\"   \"7365\"  \n[41] \"7366\"   \"7367\"   \"7371\"   \"7372\"   \"7378\"   \"7498\"   \"79799\"  \"83549\" \n[49] \"8824\"   \"8833\"   \"9\"      \"978\"   \n```\n\n\n:::\n:::\n\n\n\nI must speak with KEGG! Change column to ENTREZID to be intelligible to KEGG.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nres$entrez <- mapIds(org.Hs.eg.db,\n                     keys=row.names(res), \n                     keytype=\"ENSEMBL\",        \n                     column=\"ENTREZID\",        \n                     multiVals=\"first\")\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n'select()' returned 1:many mapping between keys and columns\n```\n\n\n:::\n\n```{.r .cell-code}\nhead(res)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nlog2 fold change (MLE): dex treated vs control \nWald test p-value: dex treated vs control \nDataFrame with 6 rows and 8 columns\n                  baseMean log2FoldChange     lfcSE      stat    pvalue\n                 <numeric>      <numeric> <numeric> <numeric> <numeric>\nENSG00000000003 747.194195     -0.3507030  0.168246 -2.084470 0.0371175\nENSG00000000005   0.000000             NA        NA        NA        NA\nENSG00000000419 520.134160      0.2061078  0.101059  2.039475 0.0414026\nENSG00000000457 322.664844      0.0245269  0.145145  0.168982 0.8658106\nENSG00000000460  87.682625     -0.1471420  0.257007 -0.572521 0.5669691\nENSG00000000938   0.319167     -1.7322890  3.493601 -0.495846 0.6200029\n                     padj      symbol      entrez\n                <numeric> <character> <character>\nENSG00000000003  0.163035      TSPAN6        7105\nENSG00000000005        NA        TNMD       64102\nENSG00000000419  0.176032        DPM1        8813\nENSG00000000457  0.961694       SCYL3       57147\nENSG00000000460  0.815849       FIRRM       55732\nENSG00000000938        NA         FGR        2268\n```\n\n\n:::\n:::\n\n\n\nI can now use the **gage** function to check for overlap with known KEGG pathways.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfoldchanges <- res$log2FoldChange\nnames(foldchanges) <- res$entrez\nhead(foldchanges)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       7105       64102        8813       57147       55732        2268 \n-0.35070302          NA  0.20610777  0.02452695 -0.14714205 -1.73228897 \n```\n\n\n:::\n:::\n\n\n\nLets get some results\n\n\n::: {.cell}\n\n```{.r .cell-code}\nkeggres = gage(foldchanges, gsets=kegg.sets.hs)\nattributes(keggres)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n$names\n[1] \"greater\" \"less\"    \"stats\"  \n```\n\n\n:::\n\n```{.r .cell-code}\nhead(keggres$less, 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                                      p.geomean stat.mean        p.val\nhsa05332 Graft-versus-host disease 0.0004250461 -3.473346 0.0004250461\nhsa04940 Type I diabetes mellitus  0.0017820293 -3.002352 0.0017820293\nhsa05310 Asthma                    0.0020045888 -3.009050 0.0020045888\n                                        q.val set.size         exp1\nhsa05332 Graft-versus-host disease 0.09053483       40 0.0004250461\nhsa04940 Type I diabetes mellitus  0.14232581       42 0.0017820293\nhsa05310 Asthma                    0.14232581       29 0.0020045888\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\npathview(gene.data=foldchanges, pathway.id=\"hsa05310\")\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n'select()' returned 1:1 mapping between keys and columns\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nInfo: Working in directory /Users/janiec-w/Desktop/Classes/BGGN213 Bioinformatics/pRojects/JCW_111324_Class13_genomics lab\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nInfo: Writing image file hsa05310.pathview.png\n```\n\n\n:::\n:::\n\n\n\n![Genes up/down regulated in Asthma pathways](hsa05310.pathview.png)\n\n\n",
    "supporting": [
      "JCW_111324_Class13_genomics-lab_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}